version: '3.8'
services:
  db:
    image: postgres
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'